<div class="bg-dark text-light pt-3 footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 row">
                <div class="col-4">
                    <ul class="list-unstyled">
                        <li>常见问题</li>
                        <li>注册登录</li>
                        <li>账号/密码</li>
                        <li>充值/售后</li>
                        <li>题库测试</li>
                    </ul>
                </div>
                <div class="col-4">
                    <ul class="list-unstyled">
                        <li>关于14ke</li>
                        <li>关于我们</li>
                        <li>加入我们</li>
                        <li>Q群联盟</li>
                    </ul>
                </div>
                <div class="col-4">
                    <ul class="list-unstyled">
                        <li>产品服务</li>
                        <li>官方博客</li>
                        <li>帮助中心</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-4">
                <ul class="list-unstyled">
                    <li>客服咨询</li>
                    <li>400-9987011（9:30-18:30）</li>
                    <li>14keeducation@163.com</li>
                    <li class="mt-2"><a class="btn btn-primary into"><img src="/ico/qq.svg">点击进入Q群联盟</a></li>
                </ul>
            </div>
        </div>
    </div>
    <hr class="bg-light">
    <div class="container statement">
        <div class="row">
            <div class="col-md-4"><a href="#" class="text-light mr-4">注册声明</a><a href="#" class="text-light mr-4">版权申明</a><a href="#" class="text-light">售后服务</a></div>
            <div class="col-md-8 text-right"><span>办学许可证：111010873931661，电信与信息业务经营许可证：渝ICP证150109号</span></div>
        </div>
    </div>
</div>